---
AWSTemplateFormatVersion: "2010-09-09"
Description: Example of using exported output

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-01720b5f421cf0179
      InstanceType: t2.micro
      SecurityGroups:
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html
        - !ImportValue SecurityGroupId

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
Outputs:
  InstanceId:
    Description: EC2 instance ID
    Value: !Ref EC2Instance
    # NOT exported - can not be referenced by other stacks
...
