---
AWSTemplateFormatVersion: "2010-09-09"
Description: Example of using mapping with EC2 instance creation

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, test, prod]

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html
Mappings:
  Region2AMI:
    eu-west-1:
      ami: "ami-01720b5f421cf0179"
    eu-west-2:
      ami: "ami-0e80a462ede03e653"
    eu-west-3:
      ami: "ami-000bdaf1845abe910"
    eu-north-1:
      ami: "ami-01d2b64cb4bdfe5db"
    eu-south-1:
      ami: "ami-04a490111f1f73f3a"
    eu-central-1:
      ami: "ami-03c3a7e4263fd998c"
  InstanceType2Environment:
    dev:
      type: "t2.micro"
    test:
      type: "t2.small"
    prod:
      type: "t2.medium"

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-findinmap.html
      ImageId: !FindInMap [Region2AMI, !Ref AWS::Region, ami]
      InstanceType: !FindInMap [InstanceType2Environment, !Ref Environment, type]

Outputs:
  InstanceId:
    Description: EC2 instance ID
    Value: !Ref EC2Instance
...
