---
AWSTemplateFormatVersion: "2010-09-09"
Description: Example of template with metadata for AWS Console (groupping parameters)

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:

  # String + default
  SecuritygroupDescriptionParameter:
    Type: String
    Description: Security group description
    Default: My security group

  # Number + validation
  SecurityGroupPortParameter:
    Type: Number
    Description: Security group port
    Default: 8080
    MinValue: 1150
    MaxValue: 65535

  # String + validation + default
  SecurityGroupIngressCIDRParameter:
    Type: String
    Description: Securoty group ingress CIDR
    Default: 0.0.0.0/0
    MinLength: 9
    MaxLength: 18
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: invalid CIDR

  # AWS type
  SecurityGroupVPCIdParameter:
    Type: AWS::EC2::VPC::Id
    Description: VPC identifier

  # String + validation + default
  EC2InstanceTypeParameter:
    Type: String
    Description: EC2 instance type
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
    ConstraintDescription: invalid EC2 instance type

  # AWS type
  EC2KeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 instance SSH key
    ConstraintDescription: invalid key pair name

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-reference.html
Resources:

  # EC2 instance
  MyInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-01720b5f421cf0179" # !Ref EC2InstanceAMIParameter
      InstanceType: !Ref EC2InstanceTypeParameter # Parameter
      KeyName: !Ref EC2KeyPairNameParameter
      # Trick
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-securitygroups
      SecurityGroupIds:
        - !GetAtt MySecurityGroup.GroupId # Parameter

  # Elastic IP
  MyInstanceEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyInstance # Parameter

  # Security Group
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecuritygroupDescriptionParameter # Parameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref SecurityGroupPortParameter # Parameter
          ToPort: !Ref SecurityGroupPortParameter # Parameter
          CidrIp: !Ref SecurityGroupIngressCIDRParameter # Parameter
      VpcId: !Ref SecurityGroupVPCIdParameter # Parameter

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html#metadata-section-structure-keys
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Security Group Configuration"
        Parameters:
          - SecuritygroupDescriptionParameter
          - SecurityGroupPortParameter
          - SecurityGroupIngressCIDRParameter
          - SecurityGroupVPCIdParameter
      - Label:
          default: "EC2 Configuration"
        Parameters:
          - EC2InstanceTypeParameter
          - EC2KeyPairNameParameter
    ParameterLabels:
      SecurityGroupVPCIdParameter:
        default: "Select VPC ID"
...
