---
AWSTemplateFormatVersion: "2010-09-09"
Description: Pseudo parameters usage example
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [!Ref "AWS::AccountId", 4, "exercise", "bucket"]]

Outputs:

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html
  Region:
    Value: !Ref "AWS::Region"
  AccountId:
    Value: !Ref "AWS::AccountId"
#  NotificationARNs:
#    Value: !Ref "AWS::NotificationARNs"
#  NoValue:
#    Value: !Ref "AWS::NoValue" # Used with Fn::If / !If
  Partition:
    Value: !Ref "AWS::Partition"
  URLSuffix:
    Value: !Ref "AWS::URLSuffix"
  StackId:
    Value: !Ref "AWS::StackId"
  StackName:
    Value: !Ref "AWS::StackName"
...
