---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Example 1 :: running EC2 instance with custom SSH and HTTP/HTTPS Security Group"
Resources:

  # EC2 instance
  MyInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: "eu-west-1a"
      ImageId: "ami-01720b5f421cf0179"
      InstanceType: "t2.micro"
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref HTTPSecurityGroup

  # Elastic IP
  MyInstanceEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyInstance

  # SSH Security Group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Ssh Access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  # Http/Https Security Group
  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Http/Https Access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
...
