---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Example 1 :: running EC2 instance with defaults"

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-reference.html
Resources:

  # EC2 instance
  MyInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: "eu-west-1a"
      ImageId: "ami-01720b5f421cf0179"
      InstanceType: "t2.micro"
...
