---
AWSTemplateFormatVersion: "2010-09-09"
Description: Example of using conditions with EC2 instance creation

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, test, prod]
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
    ConstraintDescription: must be a valid EC2 instance type.

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/rules-section-structure.html
Rules:
  devRule:
    RuleCondition: !Equals
      - !Ref Environment
      - dev
    Assertions:
      - Assert:
          "Fn::Contains":
            - - t2.micro
            - !Ref InstanceType
        AssertDescription: 'For a dev environment, the instance type must be t2.micro'
  prodRule:
    RuleCondition: !Equals
      - !Ref Environment
      - prod
    Assertions:
      - Assert:
          "Fn::Contains":
            - - t2.medium
            - !Ref InstanceType
        AssertDescription: 'For a test environment, the instance type must be t2.medium'

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-01720b5f421cf0179"
      InstanceType: !Ref InstanceType

Outputs:
  InstanceId:
    Description: EC2 instance ID
    Value: !Ref EC2Instance
...
