---
AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Example of using nexted stacks
  S3 Bucket needs to be created manually (pduleba-cloud-formation-sl-s3-bucket)
  Cloud Formation nested stack needs to be uploaded manually (nested-stack/security-group.yaml)

Parameters:

  IngressCIDRParameter:
    Type: String
    Description: Securoty group ingress CIDR
    Default: 0.0.0.0/0
    MinLength: 9
    MaxLength: 18
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: invalid CIDR

  VPCIdParameter:
    Type: AWS::EC2::VPC::Id
    Description: VPC identifier

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-01720b5f421cf0179
      InstanceType: t2.micro
      # https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-nested-stacks-values/
      SecurityGroupIds:
        - !GetAtt SecurityGroupNestedStack.Outputs.Id

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-nested-stacks.html
  SecurityGroupNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/pduleba-cloud-formation-sl-s3-bucket/security-group.yaml
      Parameters:
        DescriptionParameter: !Sub Security group for ${AWS::StackName} # Dynamic parameter usage example
        # PortParameter:                                                # Use Default parameter of nested stack usage example
        IngressCIDRParameter: !Ref IngressCIDRParameter                 # Parameter usage example
        VPCIdParameter: !Ref VPCIdParameter                             # Parameter usage example
      TimeoutInMinutes: 5


Outputs:
  InstanceId:
    Description: EC2 instance ID
    Value: !Ref EC2Instance
  SecurityGroupId:
    Description: EC2 instance security group ID
    Value: !Ref SecurityGroupNestedStack
...
